# Harbor authentication
harbor_hostname: ""
harbor_username: admin
harbor_password: ""

# LDAP configuration
ldap_url: ""
ldap_search_dn: ""
ldap_search_password: ""
ldap_base_dn: ""
ldap_filter: objectclass=person
ldap_uid: sAMAccountName
ldap_scope: 2 # Subtree
ldap_group_base_dn: ""
ldap_group_search_filter: objectclass=group
ldap_group_attribute_name: sAMAccountName
ldap_group_admin_dn: ""
ldap_group_membership_attribute: memberof
ldap_group_search_scope: 2 # Subtree
ldap_verify_cert: true
