apiVersion: v1
kind: Secret
metadata:
  name: ca-cert
  namespace: harbor
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDojCCAoqgAwIBAgIQSQ5hCqC2GqhFn+ZNGqdPkTANBgkqhkiG9w0BAQsFADBP
    MRQwEgYKCZImiZPyLGQBGRYEZGVtbzEXMBUGCgmSJomT8ixkARkWB3RlcmFza3kx
    HjAcBgNVBAMTFXRlcmFza3ktREVNTy1EQy0wMS1DQTAgFw0yMjA2MjQxMDIzMjla
    GA8yMDcyMDYyMzEw....
    -----END CERTIFICATE-----
