#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"harbor-core"}}),expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: core
        volumeMounts:
        #@overlay/append
        - mountPath: /etc/harbor/ssl/ldaps
          name: ldaps-cert
          readOnly: true
      volumes:
      #@overlay/append
      - name: ldaps-cert
        secret:
          secretName: harbor-ldaps-cert
          defaultMode: 420
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-ldaps-cert
  namespace: tanzu-system-registry
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDojCCAoqgAwIBAgIQSQ5hCqC2GqhFn+ZNGqdPkTANBgkqhkiG9w0BAQsFADBP
    MRQwEgYKCZImiZPyLGQBGRYEZGVtbzEXMBUGCgmSJomT8ixkARkWB3RlcmFza3kx
    HjAcBgNVBAMTFXRlcmFza3ktREVNTy1EQy0wMS1DQTAgFw0yMjA2MjQxMDIzMjla
    GA8yMDcyMDYyMzEw....
    -----END CERTIFICATE-----
